[Global]
ActualitzacioEnCurs=Actualització en curs ...'%s'
ActualitzacioKO=Hi ha hagut un problema a l'hora d'actualitzar les dades.
ActualitzacioOK=Les dades s'han actualitzat correctament.
AnyIncorrecte=Any incorrecte.
CampNoBlancs=El camp ha de ser diferent de blancs.
CampNoZero=El camp ha de ser diferent de zero.
CapDadaPerImprimir=No hi ha cap dada per imprimir.\nCanvieu els criteris de selecció.
CodiNoBlancs=El codi no pot estar a blanc.
ClientDeBaixa=El client està donat de baixa.
CrearObrirFitxer=No s'ha pogut crear o obrir el fitxer '%s'.
DadesCorrectes=Totes les dades son correctes?
DataIncorrecta=La data és incorrecta.
DataNoBlancs=La data ha de ser diferent de blancs.
DesbloquejarRegistre=Un registre del fitxer '%s' està bloquejat per un altre usuari o un altre procés.\nDesbloquejeu-lo i premeu el botó per poder continuar. 
ErrorINI=El fitxer d'inicialització '%s' conté un error.\nSortint del programa.
EscollirValor=S'ha d'escollir un valor dins la llista.
FinalFitxer=Heu arribat al final del fitxer.
FitxerBuit=El fitxer no conté cap dada.
GuardarKO=Hi ha hagut un problema a l'hora de guardar les dades.
GuardarOK=Les dades s'han guardat correctament.
HoraIncorrecta=L'hora és incorrecta.
HoraNoBlancs=L'hora ha de ser diferent de blancs.
ImpossibleCalcularPreuCostMig=Ha sigut impossible calcular el preu cost mig de l'article '%s'.
InterrompreTractament=Voleu interrompre el tractament en curs?
LimitarFiltre=Heu d'escollir algún criteri per limitar els registres a tractar.
LlestPerConsulta=Utilitzeu les fletxes per consultar els altres registres.
LlestPerCreacioFitxa=Ompliu els camps i valideu la fitxa.
LlestPerModifFitxa=Efectueu les modificacions i valideu els canvis.
MesIncorrecte=Mes incorrecte.
MissatgePrograma=Missatge del programa
ModificacioRegBaixa=El registre està donat de baixa. Suprimiu la data de baixa per poder modificar-lo.
NoDinsLimits=Els valors correctes per aquest camp es situen entre el %s i el %s.
NoSeleccionarRegistre=No es pot seleccionar aquest registre, està donat de baixa.
OpcionsObligatories=Les opcions d'inicialització son obligatories.\nSortint del programa.
PerdreModificacions=Està segur de voler descartar les modificacions?
PeriodeTancat=Període tancat per la data indicada.
PossiblesValors=Els possibles valors son %s.
PrgSetupInexistent=El programa d'instal·lació '%s' no existeix.
PrincipiFitxer=Heu arribat al principi del fitxer.
RefrescarDades=Premeu <F5> per prendre en compte els criteris seleccionats.
RegFitxerInexistent=No s'ha trobat el registre '%s' del fitxer '%s'.
RegistreDesaparegut=Aquest registre ja no es troba dins la base de dades.\nVol tornar a crear-lo de nou?
RegistreInexistent=No s'ha trobat aquest registre dins la base de dades.
RegistreJaBloquejat=Un registre del fitxer '%s' està bloquejat per un altre usuari. Voleu que ho torni a intentar?
RegistresSuprimits=S'han suprimit %s registres correctament.
RegistresTractats=S'ha(n) tractat %s registre(s).
RepFitxersInexistent=La carpeta de fitxers '%s' no existeix.
SeleccionarFacturacio=Seleccionar facturació.
SeleccionarUnaOpcio=Heu de seleccionar com a mínim una de les opcions ofertes.
SuprimirRegistre=Confirmeu la supressió del registre seleccionat?
SuprimirRegistres=Confirmeu la supressió de tots els registres seleccionats?
TascaServeiTecnic=Només hauria d'utilitzar aquesta opció sota la supervisió d'un tècnic d'AndorSoft.\nConfirmeu l'execució del tractament?
TractamentEnCurs=Tractament en curs ... '%s'
DataGestioIncorrecte=Data '%s' incorrecte.
MesErroni=<missatge no definit>
DadesFinalsInferiorsInicials=<missatge no definit>
AnyErroni=<missatge no definit>

[Articles]
ArticleDeBaixa=Aquest article està donat de baixa.
ArticleNoDinsNegoci=Aquest article no es troba dins el negoci seleccionat.
ArticleRefApuntaASiMateix=L'article de referència apunta a si mateix.
ArticleRefApuntaCiclic=L'article de referència apunta a un article que apunta a l'article en curs.
ArticleSenseCostMig=Aquest article no té preu cost mig, no es pot seleccionar.
ArticleSensePreu=No s'ha trobat el preu d'aquest article.
BarCodeErrorDigit=El digit de control és incorrecte. El codi no és vàlid.
BarCodeErrorDuplicat=Aquest codi de barra ja està otorgat a l'article '%s'.
BarCodeErrorLlargada=La llargada del codi de barra és incorrecta. Només es tracten els codis de barra de 8 i 13 xifres (EAN8 i EAN13).
BarCodeInexistent=No s'ha trobat el codi de barra %s dins la base de dades.
CanviarReferencies=Confirmeu el canvi de les referències del proveïdor %s\na partir del fitxer d'importació '%s'?.
ErrorModificacioReferencia=No s'ha pogut modificar l'antiga referència '%s' per la nova referència '%s'.
ErrorSupressioReferencia=No s'ha pogut suprimir la referència '%s'.
ImpressoraJoieria=Heu verificat que estigui correctament escollida\nla impressora per etiquetes de joieria?
IndicarBotigues=Heu d'indicar les botigues a tractar.
NoBaixaSiEstoc=No es pot donar de baixa un article si té un estoc diferent de 0.
NoEsMateriaPrima=Aquest article no és una matèria prima.
NoSeleccionarArticle=No es pot seleccionar aquest article.
NoTipusNegoci=Heu d'indicar com a mínim un tipus de negoci.
RecalcularTarifes=Confirmeu el recàlcul de la tarifa '%s' a partir de les dades indicades?
RecalculTarifaOK=El recàlcul de la tarifa '%s' s'ha completat satisfactoriament.		
ReferenciesCanviades=El canvi de referències s'ha completat correctament.\nS'han trobat %s referències dins el fitxer d'importació\nque han permès modificar %s referències i suprimir %s referències.
SuprimirAutor=L'autor seleccionat no es pot suprimir, ja que està referenciat per un article.
SuprimirMarca=La marca seleccionada no es pot suprimir, ja que està referenciada per un article.
SuprimirReferencia=Segons el fitxer d'importació, s'ha de suprimir la referència '%s' del proveïdor.\nConfirmeu aquesta supressió?
SuprimirTotesReferencies=Confirmeu la supressió de totes les referències indicades dins el fitxer?
SuprimirTractats=Confirmeu la supressió dels registres marcats com a tractats?
TipusArticleInvalid=El tipus d'article indicat és invalid per aquest tipus de negoci.
BaixaProces=Està segur de voler donar de baixa els articles seleccionats ?
BaixaProcesEnCurs=Donant de baixa article '%s - %s'
BaixaProcesOK=%s article(s) donats de baixa.
ArticleFaltaEstoc=L'article no té cap linia de estoc pel negoci demanat.
TMInferior1=Tm inferior
;15-12-2012
ArticleSenseIGI=Article %s no té IGI definit.

[Compres]
ActualitzarConfrontacio=Està segur de voler actualitzar la confrontació nº%s?
ActualitzarEntrades=Confirmeu l'actualització de les entrades seleccionades del negoci '%s'?
ActualitzantEntrada=Actualitzant l'entrada %s ...
AlgunaDespesaAmbPercentatge=Atenció: \nHi ha alguna despesa amb percentatge sobre l'import.\nEs recalcularan les despeses amb percentatge.
ArticleDiferentProveidor=Article d'un altre proveïdor.
ArticleNoDeCompra=Aquest article no es pot comprar.
ArticleNoIntegrat=Article %s ignorat, no te cap proveïdor assignat.
CaixesIOUnitats=S'ha d'informar les caixes i/o les unitats.
CancelComanda=Està segur de voler cancel·lar la comanda nº%s?
CancelEntrada=Està segur de voler cancel·lar l'entrada nº%s?
CapPeriodePerTancar=No hi ha cap període per tancar.
CapPeticioAIntegrar=No s'ha trobat cap petició de comanda per integrar.
ComandaSenseLinies=La comanda nº%s no tè cap línia de detall d'articles.
DataComandaPosteriorPrevisio=Data comanda posterior a data previsió.
DataDocumentPosteriorEntrada=La data del document és posterior a la data d'entrada.
DataRecepcioPosteriorEntrada=La data de recepció és posterior a la data d'entrada.
EnviarComanda=Està segur de voler enviar la comanda nº%s?
ErrorConfrontacio=Entrada '%s' no es pot confrontar.\nNo trobada o ja confrontada.
IntegrarComanda=Està segur de voler integrar la comanda nº%s?
IntegrarPeticionsComandes=Està segur de voler integrar les peticions de comandes?
IntegrarPeticionsComandesKO=Al menys un article no s'ha pogut tractar.
IntegrarPeticionsComandesOK=Procès d'integració de peticions de comandes acabada correctament.
MonedaDiferentaProveidor=Moneda diferent a moneda proveïdor. 
NoCanviProveidor=No es pot canviar el proveidor, ja s'han entrat línies.
NoCanviProveidorJaArticles=No es pot canviar el proveidor, ja s'han entrat línies d'articles.
RecalcularTaulaVenciments=Voleu recalcular la taula dels venciments?
SuprimirConformacio=Confirmeu la supressió de la confrontació seleccionada?
TotalVencimentsNoQuadren=Total venciments del detall no quadra.
DocumentProveidorJaExistent=Document proveïdor ja existent per entrada nº%s.
NumeroDuanaSubmissioObligatori=Nº duana o Nº submissió obligatori.
DuanaObligatoria=Duana obligatòria.
ImprimirEtiquetes=Imprimir les etiquetes de la cessi¢ en curs ?
ImpressioEtiquetesOK=Impressió etiquetes efectuada correctament.
ImpossibleImprimirEtiquetes=Impossible imprimir etiquetes per la botiga demanada.
BotigaDeBaixa=Botiga de baixa
ImportDretsDuanersObligatoris=Drets duaners obligatoris.
IGIDuanaObligatori=IGI duana obligatori.
IGIObligatori=IGI obligatori.
TotalIGINoQuadren=Total IGI no quadren.
ArticleAmbTipusIGINoIntroduit=Existeixen articles amb el tipus impositiu %s no introduïts
NoExisteixArticleAmbTipusIGI=No existeix cap article amb el tipus impositiu %s.
ArticleSenseTipusImpositiu=L'article %s no té associat cap tipus impositiu.
DataDUAObligatori=Data DUA obligatòria.
IGIMonedaIncompatibles=IGI Moneda incompatibles.
NoCanviMoneda=Canvi moneda no trobat.
QuotaManualIncorrecte=Quota
ArticleDeBaixa=<missatge no definit>
ProveidorDeBaixa=<missatge no definit>

[Comptabilitzacions]
AssentamentsSuprimits=S'han suprimit %s assentaments i %s apunts correctament.
CfgDiariJaExistent=Aquest orígen de comptabilització ja està atribuit al diari '%s'.
CfgDiariNoTrobat=No s'ha trobat la referència de diari '%s/%s' per la societat en curs.
CfgErrorGuardar=No s'han pogut guardar les dades al fitxer de configuració per una raó desconeguda.
CfgExcepcioJaExistent=Aquesta excepció ja està matriculada amb el destí '%s'.
CfgExcepcioNoTrobada=No s'ha trobat l'excepció '%s/%s' per la societat en curs.
CfgSocietatJaExistent=Aquest codi societat ja està atribuit per\nla configuració de la societat comptable '%s'.
CfgSocietatNoTrobada=No s'ha trobat el fitxer de configuració de la societat '%s'.
CfgSuprimirConfig=Confirmeu la supressió del fitxer de configuració\nde la societat comptable '%s: %s'?
CfgSuprimirDiari=Confirmeu la supressió de la referència de diari '%s: %s'?
CfgSuprimirExcepcio=Confirmeu la supressió de l'excepció '%s/%s'?
CfgSuprimirTipusApunt=Confirmeu la supressió del tipus d'apunt '%s: %s'?
CfgTipusApuntJaExistent=Aquest codi ja està atribuit al tipus d'apunt '%s'.
CfgTipusApuntNoTrobat=No s'ha trobat el tipus d'apunt '%s' per la societat en curs.
ExportantSocietat=Exportant les dades de la societat comptable '%s' ...
ExportarAssentaments=Confirmeu l'exportació dels assentaments implicats?
SentitIncorrecte=El tipus de sentit és incorrecte. Els valors admesos son 'C' i 'D'.
SuprimirAssentaments=Confirmeu la supressió definitiva dels assentaments implicats?
TipusApuntIncorrecte=No s'ha trobat aquest tipus d'apunt dins el fitxer de configuració d'aquesta societat comptable.

[Dat]
ErrorComprimirFitxer=** No s'ha pogut comprimir el fitxer '%s'.
ErrorCopiarFitxer=** No s'ha pogut copiar el fitxer '%s' dins '%s'.
ErrorCrearFitxer=** No s'ha pogut crear el fitxer '%s'.
ErrorDatCorromput=** El fitxer de dades '%s' està corromput.
ErrorEscriureFitxer=** No es pot escriure dins el fitxer '%s'.
ErrorFitxerNoIndicat=** No s'ha indicat el nom del fitxer .dat a tractar.
ErrorObrirFitxer=** No s'ha pogut obrir el fitxer '%s'.
ErrorSuprimirFitxer=** No s'ha pogut suprimir el fitxer '%s'.
TempNoCreat=** No s'ha pogut trobar un nom pel fitxer temporal.

[Factures]
CancelFactura=Al cancel·lar una factura es cancel·laran també\ntots els albarans associats que encara no s'hagin cobrat.\n\nConfirmeu la cancel·lació de la factura '%s'?
CapAlbaraPerFacturar=No s'ha trobat cap albarà per facturar amb els paràmetres indicats.
CobrarFactura=Al cobrar una factura es cobraran també\ntots els albarans associats que encara no s'hagin cobrat.\n\nConfirmeu el cobrament de la factura '%s'?
CreantFactura=Creant la factura %s (albarà: %s) ...
ExcloureAlbara=Confirmeu la exclusió de l'albarà seleccionat d'aquesta factura?
FacturacioJaFeta=Ja existeix una facturació del negoci %s per la data %s.\nContinuar amb el procés?
FacturacioOK=El procés de facturació s'ha acabat correctament.\nS'han creat %s factures.
FacturacioKOAmbFactures=El procés de facturació s'ha acabat incorrectament.\nTot i això s'han creat %s factures.\nÉs possible que la darrera factura del procés estigui buida.
FacturacioKOSenseFactures=El procés de facturació s'ha acabat incorrectament.\nNo s'ha creat cap factura.
FacturarPerBotiga=Confirmeu l'inici del procés de facturació per la botiga %s?
FacturarTot=Confirmeu l'inici del procés de facturació per totes les botigues del negoci %s?
FacturesSuprimides=S'han suprimit %s factures, %s albarans i %s línies d'albarà correctament.
FitxerAlbaransBloquejat=No s'ha pogut bloquejar el fitxer d'albarans ja que estava bloquejat per un altre procés.
ProcessosSuprimits=S'han suprimit %s processos de facturació, %s factures,\n%s albarans i %s línies d'albarà correctament.
SuprimirFactures=Confirmeu la supressió definitiva de les factures implicades i dels seus albarans associats, del negoci '%s'?
SuprimirProcessos=Confirmeu la supressió definitiva dels processos de facturació implicats i de les seves factures i albarans associats?

;FacturaEnCurs=Facturant albarà Nº '%s'.
;FitxerFacturacionsBloquejat=Fitxer de factures bloquejat per un altre procès.
;SeleccionarFacturacio=Seleccioneu una facturació.

[GRoBatch]
BaixaArticle=Article %s donat de baixa.
BotigajaMatriculada=La botiga indicada ja està matriculada.
BotigaNoMatriculada=La botiga %s/%s no està matriculada al servidor de la Central.
CanviNoTrobat=No s'ha trobat canvi per la moneda %s en data %s, de la factura %s.
ClientNoDisponible=** Client %s no disponible per efectuar la tasca.
ClientInexistent=El client %s és inexistent pel negoci %s (línia %s).
CobramentSenseClient=Falta el client al cobrament de la línia %s.
ComprimitCliServ=S'han comprimit els %s registres del fitxer d'exportació pel servidor de la Central dins el fitxer '%s'.
ComprimitCliTPV=S'ha comprimit el fitxer d'exportació pels TPVs dins el fitxer '%s'.
ComprimitFitxer=S'ha comprimit el fitxer '%s' dins el fitxer '%s'.
ComprimitServCli=S'han comprimit els fitxers de canvis dins el fitxer '%s'.
CreantArticleConfirmat=Creant article %s
CreantArticlesConfirmats=Creant els articles confirmats per la Central ...
CreantAutorConfirmat=Creant autor %s
CreantMarcaConfirmada=Creant marca %s
CreantNouFitxerIni=Creant el fitxer de configuració '%s'.
DadesNoPreparades=No s'han pogut preparar les dades de la botiga %s/%s.
DadesPreparadesPerEnviar=Preparació de dades concluïda.
DonantBaixaArticles=Donant de baixa els articles que no s'han utilitzat en %s mesos.\n%s registres controlats ...
ErrorBloqueigGlobal=** No s'ha pogut bloquejar la base de dades en la seva totalitat ('%s').
ErrorCanviarEstat=** No s'ha pogut canviar l'estat del servidor '%s' a '%s'.
ErrorCarpetaNoTrobada=** No s'ha trobat la carpeta '%s'.
ErrorComprimirFitxer=** No s'ha pogut comprimir el fitxer '%s'.
ErrorCopiarFitxer=** No s'ha pogut copiar el fitxer '%s' dins '%s'.
ErrorCrearCarpeta=** No s'ha pogut crear la carpeta '%s'.
ErrorCrearFitxer=** No s'ha pogut crear el fitxer '%s'.
ErrorDescomprimirFitxer=** No s'ha pogut descomprimir el fitxer '%s'.
ErrorFitxerNoTrobat=** No s'ha trobat el fitxer '%s'.
ErrorInicialitzar=No s'ha pogut inicialitzar el sistema de sincronització.
ErrorMoureFitxer=** No s'ha pogut moure el fitxer '%s' a la carpeta '%s'.
ErrorMoneda=** No s'ha trobat la moneda '%s' de la línia %s.
ErrorNumTiquet=** Error a la línia %s, el número de tiquet de la línia no correspon a la capçalera.
ErrorObrirFitxer=** No s'ha pogut obrir el fitxer '%s'.
ErrorPeriodeTancat=** El període per la data %s de la línia %s està tancat.
ErrorRenombrarFitxer=** No s'ha pogut canviar el nom del fitxer '%s' a '%s'.
ErrorSuprimirFitxer=** No s'ha pogut suprimir el fitxer '%s'.
EstatServidorCanviat=Canviat l'estat del servidor '%s' a '%s'.
FaltaParametre=** Falta un paràmetre per executar la tasca.
FiBaixaArticles=Baixa automàtica d'articles completada.
FiEnviarEmail=Fitxer '%s' enviat a '%s'.
FiGenerarCliServ=S'ha generat el fitxer d'exportació '%s' pel servidor de la Central amb %s registres.
FiGenerarCliTPV=S'han generat els fitxers d'exportació pels TPVs: %s registres.
FiGenerarServCli=S'han generat els fitxers de canvis pels clients: %s altes, %s modificacions, %s supressions.
FiIntegracioNO=Cap fitxer per integrar.
FiIntegrarCliServOK=Integració de les dades de tots els clients completada.
FiIntegrarCliServKO=Integració de les dades d'alguns clients completada.
FiIntegrarServCliOK=Integració de les dades del servidor de la Central completada.
FiIntegrarServCliKO=Integració de les dades del servidor de la Central no completada.
FiNetejarLog=Fitxer log '%s' netejat fins la data %s.
FiRecalculHistorics=Recàlcul dels històrics completat.
FiReindexant=Reindexació dels fitxers de la base de dades completada.
FiSincronitzacioOK=S'han sincronitzat les dades del fitxer '%s': %s altes, %s modificacions, %s supressions.
FiSincronitzacioNO=Cap fitxer per sincronitzar.
FiTraspasKO=Traspas de dades dels clients al servidor de la Central completat parcialment.
FiTraspasOK=Traspas de dades dels clients al servidor de la Central completat.
GenerantCliTpv=Generant els fitxers TPV pel client '%s'.
IniciBaixaArticles=Iniciant la baixa automàtica d'articles.
IniciEnviarEmail=Iniciant l'enviament d'un correu electrònic.
IniciGenerarCliServ=Iniciant la generació dels fitxers pel servidor de la Central.
IniciGenerarCliTPV=Iniciant la generació dels fitxers pels TPVs.
IniciGenerarServCli=Iniciant la generació dels fitxers de canvis pels clients.
IniciIntegracio=Iniciant l'integració de dades del fitxer GRocaExp.dat
IniciIntegrarCliServ=Iniciant l'integració de les dades clients dins la base de dades central.
IniciIntegrarServCli=Iniciant l'integració de les dades del servidor de la Central.
IniciRecalculHistorics=Iniciant el recàlcul dels històrics.
IniciReindexant=Iniciant la reindexació dels fitxers de la base de dades.
IniciSincronitzacio=Iniciant la sincronització amb les dades del servidor de la Central.
IniciTraspasCliServ=Iniciant el traspas de dades dels clients al servidor de la Central.
IniciTraspasServCli=Iniciant el traspas de dades del servidor de la Central als clients.
IntegracioCliServKO=Integració parcial de les dades al servidor de la Central.
IntegracioCliServOK=Integració total de les dades al servidor de la Central.
IntegracioServCliKO=La integració de les dades de la Central s'ha concluït amb errors.
IntegrantCliServ=Integrant les dades del client '%s'.
IntegrantFitxer=Integrant les dades del fitxer '%s' ...
LogSuprimit=Fitxer log '%s' suprimit.
OpcionsNoDefinides=Les opcions del programa no estàn definides.\nHeu d'executar primer l'aplicació principal.
PreparantHistoricArticles=Preparant el recàlcul de l'històric d'articles ...
PreparantHistoricClients=Preparant el recàlcul de l'històric de clients ...
PreparantHistoricProveidors=Preparant el recàlcul de l'històric de proveïdors ...
PreparantHistoricVenedors=Preparant el recàlcul de l'històric de venedors ...
PrepararDadesPerEnviar=Preparar les dades per que puguin ser rebudes per les botigues?
RecalculantHistoricArticles=Recalculant l'històric d'articles de la subfamília\n%s %s ...
RecalculantHistoricClients=Recalculant l'històric de clients del client\n%s (Subfamília: %s) ...
RecalculantHistoricProveidors=Recalculant l'històric de proveïdors del proveïdor\n%s (Subfamília: %s) ...
RecalculantHistoricVenedors=Recalculant l'històric de venedors del venedor\n%s (Subfamília: %s) ...
RegistreNoTrobat=** No s'ha trobat el registre %s dins el fitxer '%s' utilitzant la clau '%s'.
Reindex=Recalculant l'històric d'articles de la subfamília\n%s %s ...
ReindexantFitxer=Reindexant el fitxer %s (%s) ...
ReinicialitzarEstat=Està segur de voler reinicialitzar l'estat?
SistemaNoDisponible=** Sistema no disponible per efectuar la tasca '%s'.
SupressioArticle=Article %s i totes les seves referències suprimits.
SuprimintArticles=Suprimint articles que estan de baixa des de fa %s mesos com a mínim.\n%s registres controlats ...
SuprimirClient=Està segur de voler suprimir el client '%s'?
TascaDesconeguda=** Tasca '%s' desconeguda.
TempNoCreat=** No s'ha pogut trobar un nom pel fitxer temporal.
TipusCobramentNoTrobat=No s'ha trobat el tipus de cobrament '%s' a la linia %s.
TipusLiniaNoTractat=** Tipus de registre '%s' no tractat a la línia %s.
TractantFitxer=Tractant el fitxer '%s'.
TractantRegistre=%s registres tractats ...
TraspasCliServKO=** Error %s durant el traspàs del client '%s' al servidor de la Central. Es tornarà a provar més tard.
TraspasCliServOK=Traspàs del client '%s' al servidor de la Central completat.
TraspasServCliKO=** Error %s durant el traspàs del servidor de la Central al client '%s'. Es tornarà a provar més tard.
TraspasServCliOK=Traspàs del servidor de la Central al client '%s' completat.

[Login]
ContrasenyaIncorrecta=La contrasenya és incorrecta per aquest usuari.
IdentificacioIncorrecta=Dades d'identificació de l'usuari incorrectes.\nSortint del programa.
UsuariNoTrobat=Aquest usuari no està matriculat.
UsuariObligatori=És obligatori entrar l'usuari.

[MovimentsTabac]
ArticleNoTabac=Aquest article no pertany al grup d'articles de tabac que s'ha de controlar.
CapDadaPerExportar=No s'ha trobat cap dada per exportar.
ErrorCrearCarpeta=No s'ha pogut crear la carpeta '%s'.
ErrorCrearFitxer=No s'ha pogut crear el fitxer '%s'.
ExportarMoviments=Confirmeu l'exportació dels moviments implicats?
MovimentsExportats=S'han exportat %s moviments de tabac.
MovimentsSuprimits=S'han suprimit %s moviments de tabac.
SuprimirMoviments=Confirmeu la supressió definitiva dels moviments implicats?

[PeticioArticles]
AnullarPeticions=Confirmeu l'anul·lació de les peticions seleccionades?
CanviEstat=El canvi d'estat d'una petició, és a dir confirmar una petició previament anul·lada\no anul·lar una petició previament confirmada, serà pres en compte\nnomés si encara no s'ha efectuat la exportació de dita petició.
CapDadaPerExportar=No s'ha trobat cap dada per exportar.
ClientNoMatriculat=Aquesta botiga no està matriculada al servidor de la Central.
ConfirmarPeticions=El confirmar una petició implica la creació automàtica de l'article\namb les dades indicades i l'enviament del resultat cap a la botiga sol·licitant.\nEn el cas de que una petició ja estigui confirmada, no es tornarà a crear l'article.\nVoleu confirmar totes les peticions seleccionades?
ConnectarAmbCentral=Confirmeu la connexió amb la Central per intercanviar les dades preparades?
CreacioMarcaAutorBotiga=Heu demanat la creació d'una marca o d'un autor.\nEspereu a rebre la confirmació de creació d'aquesta marca/autor per part de la Central\nabans de preparar més peticions amb la mateixa marca/autor\no sinò el servidor de la Central crearà varies vegades la mateixa marca/autor.
CreacioMarcaAutorCentral=Heu demanat la creació d'una marca o d'un autor.\nVerifiqueu que no hi hagi cap petició per confirmar amb la mateixa marca/autor\no sinó es crearà varies vegades la mateixa marca/autor.\n\nEn el cas de trobar una altra petició amb aquesta marca/autor,\nhaureu de substituir manualment la descripció, pel codi real de la marca/autor.
DadesNoExportades=No s'han pogut preparar les dades per exportar cap a la central.
DadesNoPreparades=No s'han pogut preparar les dades per exportar cap a les botigues.
ErrorCopiarFitxers=No s'han pogut copiar els fitxers '%s' a la carpeta '%s'.
ErrorCrearCarpeta=No s'ha pogut crear la carpeta '%s'.
ErrorMoureFitxers=No s'han pogut moure els fitxers '%s' a la carpeta '%s'.
ErrorSuprimirFitxer=No s'ha pogut suprimir el fitxer '%s'.
EstatNoSeleccionable=No es pot seleccionar aquest estat pel tractament en curs.
ExportarPeticions=Confirmeu l'exportació de les peticions implicades?
IntercanviCompletat=Intercanvi de dades amb el servidor de la Central concluït.
PeticionsExportades=S'han exportat %s peticions de creació d'article.\nPenseu a enviar-les a la Central. Si no ho feu, ja s'enviaran automàticament durant la nit
PeticionsSuprimides=S'han suprimit %s peticions de creació d'article i %s propietats correctament.
ServidorCentralNoDisponible=El servidor de la central no està disponible en aquests moments.\nEstat actual: '%s'.\nProveu-ho una mica més tard si us plau.
ServidorNoDisponible=El servidor no està disponible en aquests moments.\nEstat actual: '%s'.\nProveu-ho una mica més tard si us plau.
SuprimirPeticions=Confirmeu la supressió definitiva de les peticions implicades?

[Regularitzacions]
AppendFitxerExportacio=Ja existeix un fitxer d'exportació.\nTé dues opcions: buidar el fitxer existent o afegir la cessió al fitxer existent.\nSi ja ha portat aquest fitxer a la Central, s'aconsella buidar el fitxer,\nsinó pot passar que a la Central es dupliquin les cessions que ja es trobaven dins el fitxer.\n\nSi contesta 'Si', s'afegirà la cessió al fitxer existent,\nsi contesta 'No', es buidarà el fitxer i s'afegirà la cessió dins un fitxer nou.
ArticleSenseEstoc=No es pot regularitzar un article sense entrada a l'estoc.
ArticleSenseTarifa=No es pot regularitzar un article sense tarifa.
ActualitzantCessio=Actualitzant la cessió %s ...
ActualitzantRegularitzacio=Regularitzant el moviment %s ...
ActualitzarCessio=Confirmeu l'actualització de la cessió seleccionada?
ActualitzarCessions=Confirmeu l'actualització de totes les cessions en transit del negoci '%s'?
CancelCessio=Confirmeu la cancel·lació de la cessió '%s'?
CalcularPreuCostMig=Abans de tancar el moviment, voleu executar el procés de càlcul del preu cost mig\npels articles del moviment %s, que tenen el preu cost mig a 0?
CessioExportada=La cessió %s s'ha exportat correctament dins el fitxer '%s'.
CessioJaImportada=Ja existeix una cessió amb número de document '%s' pel negoci %s.\nAquesta cessió no s'importarà.
CessionsImportades=S'han importat correctament %s cessions del fitxer '%s'.
CessioMateixaBotiga=Les botigues d'orígen i de destí han de ser diferents.
CessioNoExportada=La cessió %s no s'ha pogut exportar correctament.
CessionsSuprimits=S'han suprimit %s cessions i %s línies correctament.
ConfirmarTancamentInventari=En el cas d'un inventari, es dona per sentat que tots els articles de l'inventari han sigut inventariats.\nL'estoc dels articles no inventariats s'inicialitzarà a 0.\nSegur que confirmeu el tancament?
EnviarCessio=Està segur de voler enviar la cessió nº%s?
ErrorActualitzantCessio=Error actualitzant la cessió %s.\n%s
ErrorActualitzantRegul=Error regularitzant el moviment %s.\n%s
ErrorSuprimirFitxer=No s'ha pogut suprimir el fitxer '%s'.
ExportarCessio=Està segur de voler exportar la cessió nº%s?
MateixaBotiga=La botiga destí no pot ser la matexa d'origen.
NetejantRegularitzacio=Eliminant els articles amb estoc correcte de la regularització %s ...
RegularitzacionsSuprimits=S'han suprimit %s regularitzacions i %s línies correctament.
RegularitzarMoviment=Confirmeu la regularització del moviment seleccionat?
RegularitzarMoviments=Confirmeu la regularització de tots els moviments en curs del negoci '%s'?
SuprimirCessions=Confirmeu la supressió definitiva de les cessions implicades del negoci '%s'?
SuprimirRegularitzacions=Confirmeu la supressió definitiva de les regularitzacions implicades del negoci '%s'?
TancarMoviment=Confirmeu el tancament del moviment %s?\nEl fet de tancar un moviment implica que ja no es podrà efectuar cap modificació a les línies del moviment.
ImprimirEtiquetes=Imprimir les etiquetes de la cessió en curs ?
ImpressioEtiquetesOK=Impressió etiquetes efectuada correctament.
ImpossibleImprimirEtiquetes=Impossible imprimir etiquetes per la botiga demanada.
ArticlesRepetits=Cap article inclòs. Existeixen articles repetits.
NombreArticlesInclosos=S'han inclòs %s articles.

[Remeses]
ActualitzantRemeses=Actualitzant les remeses i els %s efectes associats ...
AjornarEfectes=Confirmeu l'ajornament dels efectes seleccionats?
AlliberarEfectes=Confirmeu l'alliberament dels efectes seleccionats?
CancelEfecte=Confirmeu la cancel·lació de l'efecte '%s'?
ComptabilitzantRemeses=Comptabilitzant les remeses ...
EfecteNoRemesat=No s'ha remesat l'efecte '%s' (núm. doc.: %s) perquè és trobava en fase de compensació\namb d'altres efectes i el total continuava sent negatiu.\nS'ha passat l'estat a pendent.
EfectesAjornables=Només es poden ajornar els efectes pendents o en curs.\nAl ajornar un efecte en curs, surt de la remesa en la que estava ubicat.
EfectesAlliberables=Només es poden alliberar els efectes ajornats.
EfectesCobrables=Només es poden cobrar els efectes pendents, en curs o remesats.
EfectesInclosos=La inclusió dels efectes s'ha completat correctament. S'han inclòs %s efectes.
EfectesIncluibles=Només es poden incloure dins una remesa efectes pendents.
EfectesPagables=Només es poden pagar els efectes pendents, en curs o remesats.
EfectesTractats=S'ha(n) tractat %s efecte(s) amb el numero de pagament %s.
ExcloureEfectes=Confirmeu l'exclusió dels efectes seleccionats d'aquesta remesa?
GenerantRemesesElectroniques=Generant els fitxers de remesa electrònica ...\n(només pels bancs implicats)
ImprimintCartesCompensacio=Imprimint les cartes de compensació ...
ImprimintLletres=Imprimint les lletres ...\n(només pels bancs implicats)
ImprimintRemesesExtern=Imprimint els llistats de remeses pels bancs ...
IncloureEfectes=Confirmeu la inclusió dels efectes seleccionats dins la remesa '%s'?
IncloureEfectesRemesa=Confirmeu la inclusió dels efectes que compleixen els criteris indicats dins la remesa '%s'?
MuntarPaperLletres=Munteu paper de lletres per la societat %s a la impressora: %s.\nVoleu continuar amb el procés d'impressió?
NoModifQuanRemesat=No es pot modificar una remesa ja remeseda.
NoRemesaElectronica=La societat %s no té configurada la remesa electrònica\npel banc %s. La remesa no s'efectuarà.
PeriodeTancat=Període tancat per la data indicada.
PreparantEfectesARemesar=Preparant els efectes a remesar ...
PreparacioEfectesKO=Hi ha hagut problemes al moment de preparar els efectes a remesar.
PreparacioRemeses=Confirmeu la preparació de la o les remeses indicades?
RegistresSuprimits=S'han suprimit %s registres correctament.
RemesaErrorMoneda=S'han seleccionat efectes amb monedes diferents.  
RemesaJaRemesada=Aquesta remesa ja s'ha remesat el %s.
RemesaOK=La remesa s'ha completat correctament.\nS'ha(n) tractat %s efecte(s).
SelleccionantEfectesARemesar=Sel·leccionant els efectes a remesar ..
SuprimirEfectes=Confirmeu la supressió definitiva dels efectes implicats?

[Printers.ini]
Predeterminar=Està segur de voler predeterminar el valor seleccionat?
ValorPerDefecte=Està segur de voler recuperar el valor per defecte per aquest llistat?

[RasDial]
Error602=** El port de comunicació ja està obert.
Error617=** Pendent de desconnexió.
Error623=** No trobo l'entrada de 'Acceso Telefónico a Redes'. Verifiqueu l'ortografia.
Error629=** Desconnexió remota: el servidor a rebutjat la connexió.
Error633=** El port de comunicació no està disponible.
Error638=** Error timeout: sembla que el módem distant no contesti.
Error646=** Hora de connexió restringida: el servidor no accepta la connexió actualment.
Error647=** Error account disabled: el vostre compte d'usuari ha estat desactivat. (domini NT únicament).
Error648=** Error contrasenya caducada. (domini NT únicament).
Error649=** No teniu permís de connexió distant.
Error650=** Error: el servidor no contesta.
Error676=** Línia ocupada: torneu-ho a provar més tard.
Error678=** Error no hi ha resposta: el módem distant no contesta.
Error679=** Error no hi ha portadora: la trucada ha sigut contestada però els módems no s'han pogut posar d'acord per comunicar-se.
Error680=** Error no hi ha tonalitat: probablement el módem està apagat o no està correctament connectat a la línia telefònica/digital.
Error691=** Error d'autentificació: usuari o contrasenya incorrectes.

[Syncro]
CanvisFase1=Copiant arxius a tractar dins <Syncro>\\SyWork.
CanvisFase2=Salvaguardant fitxers de canvis dins <Syncro>\\SyBackup.
CanvisFase3=Preparant canvis per la taula '%s'.
CanvisFase4=Desplaçant arxius tractats de <Syncro>\\SyWork a <Syncro>\\SyImage.
CanvisFase5=Suprimint còpia de seguretat de <Syncro>\\SyBackup.
ClasseNoInicialitzada=** No s'ha inicialitzat la classe.
ErrorCarpetaNoTrobada=** No s'ha trobat la carpeta '%s'.
ErrorClauNoTrobada=** No s'ha pogut trobar una clau primària per la taula '%s'.
ErrorCopiarFitxer=** No s'ha pogut copiar el fitxer '%s' dins '%s'.
ErrorCopiarRegistre=** No s'ha pogut copiar un registre de '%s' a '%s'.
ErrorCrearAlias=** No s'ha pogut crear l'alias '%s'.
ErrorCrearCarpeta=** No s'ha pogut crear la carpeta '%s'.
ErrorFitxerNoTrobat=** No s'ha trobat el fitxer '%s'.
ErrorIntegritat=** Error d'integritat o de duplicats al efectuar una %s en la taula '%s'
ErrorMoureFitxer=** No s'ha pogut desplaçar el fitxer '%s' dins '%s'.
ErrorObrirTaula=** No s'ha pogut obrir la taula '%s'.
ErrorPrepararCanvis=** No s'han pogut preparar els fitxers de canvis per la taula '%s'.
ErrorSincronitzacio=** No s'han pogut sincronitzar els canvis per la taula '%s'.
ErrorSuprimirFitxer=** No s'ha pogut suprimir el fitxer '%s'.
ErrorTaulaNoTrobada=** No s'ha trobat la taula '%s' dins l'anàlisi.
FiCanvis=Càlcul dels canvis completat.
FiSincronitzacio=Sincronització completada.
IniciCanvis=Iniciant el càlcul dels canvis per les taules '%s'.
IniciSincronitzacio=Iniciant la sincronització per les taules '%s'.
ParametreObligatori=** No s'ha informat un paràmetre obligatori ('%s').
Resincronitzar=!!!!! Es recomana la resincronització de tot el Sistema Informàtic !!!!!
SincronitzacioFase1=Salvaguardant fitxers a sincronitzar dins <Syncro>\\SyBackup.
SincronitzacioFase2=Sincronitzant canvis per la taula '%s'.
SincronitzacioFase3=Suprimint còpia de seguretat de <Syncro>\\SyBackup.

[Tancament]
AlbaransPendents=No es pot fer el tancament.\nAl menys hi ha un albarà pendent d'actualitzar per aquest període.
CapPeriodePerTancar=No hi ha cap període per tancar.
CessionsPendents=No es pot fer el tancament.\nAl menys hi ha una cessió pendent d'actualitzar per aquest període.
ComptabilitzacioEnCurs=Comptabilitzacions per l'analítica ...
ConfrontacionsPendents=No es pot fer el tancament.\nAl menys hi ha una confrontació pendent d'actualitzar per aquest període.
DataFinalInferiorDataInici=La data final es inferior a la data inici.
DataInclosaExercici=L'exercici indicat es solapa amb una altre exercici.
EntradesPendents=No es pot fer el tancament.\nAl menys hi ha una entrada pendent d'actualitzar per aquest període.
FinalTancament=S'ha finalitzat el tancament mensual.
NoSuprimirPeriode=El període seleccionat no es pot suprimir.
RegularitzacionsPendents=No es pot fer el tancament.\nAl menys hi ha una regularització pendent d'actualitzar per aquest període.
TancamentEnCurs=Tancament en curs ...
TancarExercici=Confirmeu el tancament de l'exerci %s?
TancarPeriode=Confirmeu el tancament del mes %s?
TiquetsPendents=No es pot fer el tancament.\nAl menys hi ha un tiquet pendent d'actualitzar per aquest període.
PeriodeTancat=Periode tancat.

[TerminalPortatil]
CapDadaPerInventariar=No s'ha trobat cap dada per inventariar.
ErrorArticleDeBaixa=ERR: L'article %s està de baixa
ErrorArticleNoInventari=ERR: L'article %s no pertany a l'inventari %s
ErrorArticleNoNormal=ERR: L'article %s és un pou o un pou amb estoc
ErrorArticleNoReactivat=ERR: L'article %s estava de baixa, però no s'ha pogut reactivar
ErrorArticleNoTrobat=ERR: No s'ha trobat l'article %s
ErrorArticleSenseEstoc=ERR: L'article %s no té entrada a l'estoc per la botiga %s; no es pot regularitzar
ErrorArticleSenseTarifa=ERR: L'article %s no té tarifa per la botiga %s; no es pot regularitzar
ErrorCapcal=Error a la creació de la capçalera de regularització.
ErrorCodiBarraNoTrobat=ERR: No s'ha trobat el codi de barra %s
ErrorCreacioLOG=Error a la creació del fitxer log.
ErrorCreacioTXT=Error a la creació del fitxer temporal.
ErrorEscriureSav=Error d'escriptura dins el fitxer temporal de salvaguarda.
ErrorEscriureLog=Error d'escriptura dins el fitxer de missatges '%s'.
ErrorOberturaTXT=Error a l'obertura del fitxer '%s'.
ErrorTipusArticleIncorrecte=ERR: El tipus de l'article %s és incorrecte per un inventari
ErrorTipusEntradaIncorrecte=ERR: Dades de l'article %s entrades incorrectament; verifiqueu el seu tipus d'estoc
FiImportacio=[%s %s] Fi de l'importació del fitxer.
IniciImportacio=[%s %s] Inici de l'importació del fitxer.
InventariJaRegularitzat=Aquest inventari està tancat o ja està regularitzat.
NoEsInventari=La regularització escollida no és un inventari.
NotaArticleReactivat=NOTA: L'article %s estava de baixa, s'ha tornat ha reactivar
NotaArticleSensePreuVenda=NOTA: Falta el preu de venda per l'article %s; la quantitat indicada és %s; s'anul·la aquesta entrada
SegurExportar=Està segur de voler exportar aquestes dades?
SegurImportar=Està segur de voler importar aquestes dades?
WarningRegul=!!Warning!! El article %s ha sigut inventoriat amb una massa econòmica. Quantitat: %s (regularitzacion %s negoci %s)

[Utilitats]
ReindexarTot=Està segur de voler reindexar tots els fitxers?
Reindexat=Reindexació dels fitxers completada.
ReindexAnalisi=** El fitxer '%s' no pertany al analisi en curs.
ReindexBloqueig=** Impossible bloquejar completament el fitxer '%s' abans de la reindexació.
ReindexCreantFitxer=S'ha creat el fitxer '%s'.
ReindexFitxerAnalisi=** Fitxer '%s' desconegut dins l'analisi en curs.
ReindexKO=** Error durant la reindexació del fitxer '%s'.
ReindexLlargadaReg=** La llargada del registre del fitxer '%s' no és correcta.
ReindexMode=** Mode de reindexació pel fitxer '%s' incorrecte.
ReindexModul=** No hi han móduls per compartir els fitxers.
ReindexNo15=** Analisi compatible 1.5 no gestionable.
ReindexNoClau=** El fitxer '%s' no té cap clau per reindexar.
ReindexNoFitxer=No s'ha trobat el fitxer '%s'.\nVol aprofitar per crear-lo ara mateix?
ReindexObrir=** No s'ha pogut obrir el fitxer '%s'.
ReindexRegDolents=** Queden registres malmesos dins el fitxer '%s'.
ReindexRepertori=** Repertori físic no definit per reindexar el fitxer '%s'.
ReindexTancar=** Error durant el tancament del fitxer '%s'.
ReindexVersio=** La versió del fitxer '%s' no és correcta.

[Vendes]
ActualitzantAlbarans=Actualitzant l'albarà %s de la botiga %s ...
ActualitzantTancament=Actualitzant el tancament de caixa de la botiga\n%s del %s a les %s ...
ActualitzarAlbarans=Confirmeu l'actualització dels albarans pendents d'actualització del negoci '%s'?
ActualitzarTancament=Confirmeu l'actualització del tancament de caixa seleccionat?
ActualitzarTancaments=Confirmeu l'actualització de tots els tancaments de caixa en curs del negoci '%s'?
AlbaransSuprimits=S'han suprimit %s albarans i %s línies d'albarà correctament.
CancelAlbara=Confirmeu la cancel·lació de l'albarà '%s'?
CancelTancament=Confirmeu la cancel·lació del tancament de caixa seleccionat?
CanviIncorrecte=No s'ha trobat el canvi de la moneda.
CanviMoneda=Aquest canvi de moneda implica el recàcul de tots els imports de l'albarà, incloses les línies, tret de l'import a compte.\nLes dades es guardaràn automàticament al acabar el recàlcul.\n\nVol continuar amb el procès?
ClientMoros=Atenció: Aquest client està marcat com a morós.
CobrarAlbara=Confirmeu el cobrament de l'albarà '%s'?
CostMigSuperiorPreuVenda=El preu de cost mig %s és superior al preu de venda %s\nper l'article %s del tiquet %s\ndel tancament del dia %s a les %s, del TPV %s/%s.\n\nAixò és correcte?
CostMigSuperiorPreuVenda2=El preu de cost mig %s és superior al preu de venda %s\nper l'article %s de l'albarà %s\n\nAixò és correcte?
CrearFacturaDunAlbara=Confirmeu la creació d'una factura a partir de l'albarà '%s'?
CrearFacturaDunNoComptat=No es poden crear manualment factures a partir d'un albarà que no sigui albarà comptat.\nAquest albarà ha de passar per facturació i es crearà la factura automàticament.
ErrorActualitzant=Error actualitzant el tancament de la botiga\n%s del %s a les %s.\n%s
IncloureTancament=Confirmeu la inclusió de tots els tiquets del tancament seleccionat dins aquest tancament?\nDesprés de l'operació, el tancament seleccionat serà suprimit.
SuprimirAlbarans=Confirmeu la supressió definitiva dels albarans implicats, que no s'hagin facturat,\nde totes les botigues del negoci '%s'?
SuprimirTancaments=Confirmeu la supressió definitiva dels tancaments implicats,\nde totes les botigues del negoci '%s'?
TancamentsSuprimits=S'han suprimit %s tancaments, %s tiquets i %s línies de tiquet correctament.
TiquetEnDoble=El nº de tiquet '%s' del tancament orígen ja es troba dins el tancament destí.\nNo es pot efectuar l'operació demanada.
TiquetsInclosos=La inclusió dels tiquets s'ha completat. S'han inclós %s tiquets i %s línies de tiquet.
VerificarAlbarans=Confirmeu la verificació dels albarans pendents d'actualització?
VerificarTancaments=Confirmeu la verificació de tots els tancaments en curs o en error del negoci '%s'?
CancelTiquet=Confirmeu la cancel·lació del tiquet '%s'?

[Reparacions]
Tancar=Confirmeu el tancament del moviment nº%s?
CancelReparacio=Està segur de voler cancel·lar la reparació nº%s?
AvisDataEntregaSuperiorData= Existeixen reparacions en curs amb data d'entrega inferior a la data del dia.

[Pagaments]
DataPagamentObligatoria=Data pagament obligatori.
GenerarPagaments=Generar Pagaments ?
ImpressioPagaments=Impressió pagaments ?
IniciarImpressio=Iniciar impressió
CapEfecteXecFacturaPagareSeleccionat=Cap efecte seleccionat.
CancelPagament=Cancel·lar pagament.
ImpressioImpossible=Impressió impossible.
ReImprimir=Reeimprimir.
Retrocedir=Retrocedir pagament ?
[OperacionsTargetes]
ComptabilitzarOperacionsTargetes=<missatge no definit>
CabcelOperacionsTargetes=<missatge no definit>
PuntejarOperacionsTargetes=<missatge no definit>
[TipusProveidorNoPagamentsManuals]
Compres=<missatge no definit>
[Promocions]
GfmObligatori=<missatge no definit>
FamObligatori=<missatge no definit>
CoeficientObligatori=<missatge no definit>
DataObligatori=<missatge no definit>
DataFinalInferiorDataInici=<missatge no definit>
CancelPromocio=<missatge no definit>
ActivarPromocio=<missatge no definit>
CoeficientNoSuperiorU=<missatge no definit>
TancarPromocio=<missatge no definit>
[AvisDataEntregaSuperiorData]
Reparacions=<missatge no definit>
[LiquidacionTargetes]
ImportacioOK=<missatge no definit>
[ComptaHotels]
PuntejarControl=Puntejar dia ?
Puntejar=Puntejar dia ?
Comptabilitzar=Comptabilitzar dia seleccionat ?
ComptabilitzarPuntejats=Comptabilitzar dies puntejats ?
ImportacioOK=Importació efectuada correctament.
CancelControl=<missatge no definit>
